### ISSUE TITLE
Homekit reports as not certified

### ISSUE THREAD

**Issue by frankthechicken** [merdok/homebridge-webos-tv#104]
I can see that the plugin has correctly found the TV as it reports any changes in input (i.e.switch to HDMI) on the terminal.

However the Home App states that it is not Homekit certified and therefore it cannot be accused through the app.

Is there any workaround for this?

**Comment by basvdploeg** [comment]
Are you sure you are running the iOS 12.2 beta?

**Comment by frankthechicken** [comment]
Aaargh, I'm an idiot, sorry.  Do all the devices need to be 12.2+, or just the hub (in this case an Apple TV)?

**Comment by chris-araman** [comment]
I can confirm that hubs do not (currently) need to be iOS 12.2 or tvOS 12.2. Only the controlling device needs to be iOS 12.2. I say "currently" because the requirements may change before iOS 12.2 is released.

We have two Apple TVs running tvOS 12.1.2 and one HomePod running iOS 12.1.3 enabled as hubs. The controlling devices is an iPad running the iOS 12.2 developer beta.
