### ISSUE TITLE
Keeping appSwitch 

### ISSUE THREAD

**Issue by ryanchucks** [merdok/homebridge-webos-tv#113]
Hi, I understand the latest version has removed appSwitch in favor of inputs.

However, I hope appSwitch can be brought back because:

1. It's useful for quick switching of apps (not inputs). As it stands, pressing TV > Inputs > app is too many steps.

2. Also, the plugin doesn't go back to the last input used if that "input" is an app, such as Netflix. For actual inputs (e.g., HDMI 1, 2, etc.), yes - but not for apps.

3. Finally, appSwitch is useful of automations since it basically acts like a switch that can be toggled separately. Currently, there's no way to create a scene to turn on the TV and open an app.

Thanks for reading.

**Comment by merdok** [comment]
You can still use inputs the same way as you used appSwitch before. I have just renamed it to inputs. This way you can switch between the new tv service and old tv service without adjusting additional properties.
It just behaves different now, depending if you use the new tv service.
Of course when you use the new tv service then instead of separate switches for each input you will have to use the dedicated "Inputs" list.

What do you mean with #2?

#3 i do not like too, since like you said with the new tv service automation is not possible based on apps or input changes....

**Comment by ryanchucks** [comment]
Hi,

Did I remember correctly that in an earlier release last week both appSwitch and inputs can co-exist when tv service is set to true? While it might seem strange to have duplicates (inputs in Input list + custom inputs appearing as switches outside), this is useful for automations.

Regarding #2, I found that when I last used an app like Netflix, and I turned the TV off, the next time I turned the TV on, it would not return to Netflix. This is because only the power on command is issued; opening an app needs another command. For traditional inputs like live tv, HDMI, component, the power on command is enough because the TV itself remembers the last input used. As such, I don’t like to mix software apps and hardware inputs in the same Input list in new tv service.

**Comment by merdok** [comment]
No, that was never the case. I did not do that because of the reason that it is not really useful to have duplicates, besides the input switches would just spam the home app... 

That is the standard behavior of the TV.  If you have an app open and power off the TV it will not return to the app, it will return to the last input. If you want to start an app straight the you just have to use the input for the app, in that case the TV will power on and attempt to open the select app will be made.

**Comment by ryanchucks** [comment]
Yup, I get the rationale.

I guess I will go back to old method without tv service as I have automations that rely on input switches.

Hopefully future iOS releases will make the new tv service more automation-friendly.

**Comment by merdok** [comment]
I agree with you... I have also lost some automation since switching to the TV service. But i hope that Apple will allow automation based on inputs in some of the next beta. If not then i will think of something :)
