### ISSUE TITLE
Memory Leak error

### ISSUE THREAD

**Issue by azaiszen** [merdok/homebridge-webos-tv#118]
Hey all,

Getting this error in my hole bridge console

`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 16 undefined listeners added. Use emitter.setMaxListeners() to increase limit`

Any ideas on how to fix it? only appeared since installing this plugin.

**Comment by merdok** [comment]
You would need to provide more details about this error, like the stacktrace. So that i know if it is related to the plugin and where it is actually happening.

**Comment by azaiszen** [comment]
no worries - what is the best way to get this? I am new to all of this...

**Comment by merdok** [comment]
I am honestly not sure. Since you are the only one experiencing this issue(at least no one other reported this) you would need to find a way to provide me more info. I did a quick google about the error and there are a lot of info about it, including ways to find out more details. Maybe you could try that?

**Comment by azaiszen** [comment]
yeah - I had a good look at google before posting the issue - also, not the only one... just the only one to post here. Cheers for the help

**Comment by merdok** [comment]
So is the issue still there? Maybe this has something to do with your homebridge setup in general and not with this plugin?
