### ISSUE TITLE
Siri commands for TV inputs

### ISSUE THREAD

**Issue by mortocks** [merdok/homebridge-webos-tv#142]

**Comment by mortocks** [comment]
Not really a bug/issue. Is there a Siri command to change the input of the TV without the channelButtons option enabled? With this option enabled I’m able to say “hey Siri set the tv to PlayStation “ but I can’t seem to do this without the Chanel buttons enabled even though the inputs appear S options under the tv menu

**Comment by merdok** [comment]
Unfortunately the current implementation by Apple of the Homekit TV integration does not allow to switch inputs with Siri. In order to do that you would need to use the `channelButtons `to switch between channels or if you want to switch between inputs with Siri you would need to disable the TV service. With the "old" service for each input a switch will be added to Homekit which you control with Siri.
