### ISSUE TITLE
Synology Docker

### ISSUE THREAD

**Issue by JDogg016** [merdok/homebridge-webos-tv#144]
Anyone know what directory I should use to store the key file if you are using the configuration ui plugin for homebridge as installed on a synology docker?

**Comment by basvdploeg** [comment]
I’m using:

```"keyFile": "/homebridge/lgtvKeyFile"```

**Comment by JDogg016** [comment]
On synology? With Homebridge UI?

**Comment by r3dDoX** [comment]
This depends a bit how you configured your docker container. You most probably have a mounted volume. My setup on the Synology mounts a folder under /homebridge. So my keyfile sits under /homebridge like mentioned above by @basvdploeg.

**Comment by JDogg016** [comment]
[https://share.icloud.com/photos/0T2epwAy_WAnY3f-QifjrVMrw#Boca_Raton,_FL](url)

Here are my settings. Any ideas?

**Comment by r3dDoX** [comment]
So your settings expect the keyFile in the root directory which means you'd have to have a file '/Key.txt'. The thing about a docker container is that you have to mount a volume into the container to persist data. Otherwise with every restart of the container you potentially lose the data stored in the container.

So what you have to check is that in the Overview Tab of the Docker Container on the lower left you should find a Tab called "Volume". I for example have a mounted Volume like this:
File/Folder                          Mount path         Type
docker/homebridge           /homebridge       rw

This means on my Synology I have a folder called "docker" with a subfolder "homebridge". In the Docker Container I have a folder called "homebridge" which actually points to that folder on my Synology device. So my Keyfile is set to "/homebridge/lgtvKeyFile". As soon as I start up the container and setup the connection to my TV this plugin will create this file and it will be persisted even if I restart the Docker Container or update it or whatever. Hope that helps

**Comment by JDogg016** [comment]
So I did what you stated.  My docker container is mounted exactly as yours is docker/homebridge /homebridge rw.  My keyfile is /homebridge/lgtvKeyFile.  When I restart home bridge, this is my log:

```
[6/5/2019, 9:06:27 AM] [Family Room TV] webOS - prompt for confirmation
[6/5/2019, 9:06:29 AM] [Family Room TV] webOS - prompt for confirmation
[6/5/2019, 9:06:37 AM] [Family Room TV] webOS - prompt for confirmation
[6/5/2019, 9:06:47 AM] [Family Room TV] webOS - prompt for confirmation
[6/5/2019, 9:06:57 AM] [Family Room TV] webOS - prompt for confirmation
[6/5/2019, 9:07:07 AM] [Family Room TV] webOS - prompt for confirmation
[6/5/2019, 9:07:17 AM] [Family Room TV] webOS - prompt for confirmation
[6/5/2019, 9:07:19 AM] [Family Room TV] webOS - connected to TV
[6/5/2019, 9:07:19 AM] [Family Room TV] webOS - Error: EISDIR: illegal operation on a directory, open '/homebridge/lgtvKeyFile'
```

**Comment by cacherocks** [comment]
> Anyone know what directory I should use to store the key file if you are using the configuration ui plugin for homebridge as installed on a synology docker?

- In config.json: "keyFile": "/homebridge/lgtvKeyFile.txt"
- make file "lgtvKeyFile.txt" in dir "/docker/homebridge"
- in docker: 
<img width="629" alt="Снимок экрана 2019-07-12 в 20 04 00" src="https://user-images.githubusercontent.com/25862599/61145550-6ecbf280-a4e0-11e9-8d6c-fcb46dbd0c9c.png">

**Comment by JDogg016** [comment]
So its a permissions issue but I don't know how to grant permissions.

Here is the log:  [10/10/2019, 6:53:36 PM] [Family Room TV] webOS - Error: EACCES: permission denied, open '/root/.lgtv2/keyfile-192.168.7.63'

**Comment by piotr-tobolski** [comment]
it looks like you have some path set to home, aka: `~`
I have in my config this and it works fine:

            "keyFile": "/homebridge/lgtvKeyFile.txt",
            "prefsDir": "/homebridge/.webosTv",

I have homebridge dir mapped to `/homebridge` just like shown on screenshot above

**Comment by JVPA** [comment]
In the last tab of docker's configuration you have to add a new variable "DSN_HOSTNAME" and put the value that you have put in the configuration of your NAS in the network / configuration tab of DSM
