### ISSUE TITLE
Switches - bug or feature?

### ISSUE THREAD

**Issue by evk0122** [merdok/homebridge-webos-tv#167]
Thank you for this plugin. 

I used config.json from your examples and got everything running. However now my "Home" app is populated with a dozen of TV-related switches: switch for "CHANNELUP", switch for "CHANNELDOWN", "LEFT", "RIGHT", "UP", "DOWN", "MENU" etc. I guess this is intended behavior and all commands are supposed to be switches (apart from sound slider, which is a light bulb :D). I wondered if there might be a way for more elegant solution or are we limited to what HomeKit/Homebridge let developers do?

**Comment by merdok** [comment]
Hi,

there is no other solution currently. If you want to control so much features of a TV then we need to 
 do it in a"hacky" way since the Home app was never intended to control such devices. Right now there is the TV integration in iOS but that still just has the basic features. 
At least the advantage of the current way is that you can do automation based on the TV actions which is not possible with the iOS TV integration :)

**Comment by evk0122** [comment]
yep, so we just have to wait till Apple decides to add a more sophisticated way to control stuff from Home app. Thank you.
