### ISSUE TITLE
TV turns on when turning while prixel refreshing/screen shift

### ISSUE THREAD

**Issue by Martvvliet** [merdok/homebridge-webos-tv#171]
Hi, I have an LG OLED55B7. When I turn off the TV it will do some screen refresh functions. When this is happening homebridge detects the TV as turned on. Now when turning the TV off again, when the pixel refresh is still ongoing, the TV turns on again. In my memory, this was not the case a few months back. Do you know what causes this problem?

**Comment by merdok** [comment]
About the pixel refresh issue there is really nothing that i can do about it since there is no way to detect that state. When the pixel refresh is running the TV is actually on, just the display is off and that makes it hard to detect. So basically when the pixel refresher is running the TV will be reported as on in the home app. The positive is that the pixel refresh only runs about 9 minutes so after that time the status will automatically update to off in the home app. This was always like that.
It is best that you just do not try to turn it off or on during that time since it will not really bring anything expect turn it **really** back on again.

**Comment by Martvvliet** [comment]
How does the LG app recognise the difference between off and refreshing? Maybe that is possible to implement?

**Comment by merdok** [comment]
There a private api endpoints which are not documented. Maybe there is an API for that but we do not know about it. Someone would need to jailbreak the TV and dig in the files to find available endpoints.

**Comment by Martvvliet** [comment]
And maybe testing what kind of packages are send to the app from the TV?

**Comment by merdok** [comment]
I suppose that is not enough.
