### ISSUE TITLE
[Feature Request] "No response" status if TV is not reachable/unplugged

### ISSUE THREAD

**Issue by agneevX** [merdok/homebridge-webos-tv#221]
Hi,

Can you add an option to show "No response" to HomeKit if the TV is not reachable (`EHOSTUNREACH`) and "Off" only when the TV is actually powered off?

Thanks.

**Comment by merdok** [comment]
Why do you think a "No response" should be shown when the TV is off or not reachable? 
I think that this is not a good idea. The TV even if it is off or not reachable can be turned on with the switch so a "No response" on the switch would be a false information. This would break Siri since then you would always get a response from Siri that the device is not responding. 
Actually when i started developing this plugin the tv returned a "No response" when it was and it caused a lot of trouble and did not make sense because of that the behavior was changed.

**Comment by agneevX** [comment]
> Why do you think a "No response" should be shown when the TV is off or not reachable?

Particularly because I’ll know that the TV is unplugged and it’s not gonna come on if I tap the tile in the Home app.

Again, this should be an option and only appear when the TV cannot be turned on because it’s unplugged.

> The TV even if it is off or not reachable can be turned on with the switch

How? It’s not even plugged in to power. 

No response shows that the TV is not responding, which it can’t because it’s doesn’t have power.

**Comment by merdok** [comment]
It is not possible to know whether the TV is unplugged or off. 
If you unplugged your tv then you did it manually so in that case you should be aware that the tv will not come up when you tap the tile.

**Comment by agneevX** [comment]
> It is not possible to know whether the TV is unplugged or off.

Yes it is - `EHOSTUNREACH`.

**Comment by merdok** [comment]
This helps nothing. The tv will be always unreachable no matter if unplugged or off.

This topic has been already discussed long time ago and I believe the current implementation is the best. Like I said if you unplug your tv then you should be aware of that.
