### ISSUE TITLE
Question: TV service switches only visible in Apples Home App?

### ISSUE THREAD

**Issue by palasinio** [merdok/homebridge-webos-tv#250]
Hi, I wonder if it is an issue in my environment or if it is by design:
I can’t see may TV in EVE or Controller app.
Devices of other plugins like weather-plus or telegram are only visible in EVE or Controller app.
So this way I‘m not able to do automations without using iOS 12 / legacy mode.
Recently I switched from accessory to platform.

**Comment by merdok** [comment]
Hi,
unfortunately i do not use the Eve and Controller app so i am not sure about that. The Eve or Controller app need to support TV devices in order for that work. I know that recently there was an issue with the Eve app which was not working for some people after an update but this was caused by Eve itself, maybe that is related?

**Comment by palasinio** [comment]
I don‘t know. Hopefully there will be a Home app to be usable for all devices.
