### ISSUE TITLE
Channel names

### ISSUE THREAD

**Issue by bwalls** [merdok/homebridge-webos-tv#265]
My over-the-air channels are all digital, so tend to have numbers like 19-1, 19-2, 19-3, etc. 

I have the controls working as individual buttons, and it works okay functionally. However, when I look at all the buttons in Home on my iPhone or iPad, all I see is:
**LG OLED tv
Channel - ...**
Off

On my iMac, I can actually see the full number for the Internet channels (e.g. 141, 146), and the first digit of the two-digit - single-digit strings.

Any way to shorten "Channel" to "Ch#"?

Here is the setup
                 "channelButtons": [
                        "15-1",
                        "19-1",
                        "19-2",
                        "19-3",
                        "25-1",
                        "25-2",
                        "25-3",
                        "25-4",
                        "25-5",
                        "31-1",
                        "31-2",
                        "31-3",
                        "48-1",
                        "48-2",
                        "48-3",
                        "48-4",
                        "54-1",
                        "54-2",
                        "54-3",
                        "54-4",
                        141,
                        146,
                        362
                    ],

**Comment by merdok** [comment]
Hi,
Instead of a list of numbers, you can put an object for each of them. The object can have a  channelNumber and channelName property. In that case the channel button title will not be auto generated and the provided name will be used. Something like this:

"channelButtons": [
{
“channleNumber”: “141”,
“channleName”: “my channel”
},
{
“channleNumber”: “146”,
“channleName”: “my other channel”
}
],
