### ISSUE TITLE
Version 2.0.0 TV becomes unresponsive when leaving local WiFi

### ISSUE THREAD

**Issue by CooperCGN** [merdok/homebridge-webos-tv#285]
As the title says, as soon as I move out of the range of my wifi the TV gets the infamous no response label while at the same time it’s perfectly fine on my iPad. All other accessories behave normal. Returned to version 1.9.3 and all is working fine again. Any idea?

**Comment by merdok** [comment]
No issues at all here. 
Should not actually matter if it is in the local WiFi or not as long as you have your Apple TV or iPad setup as a bridge. Of course there will be always some lag when you are outside of your local WiFi because all the calls have to go through the bridge. So if you have bad cellular reception then that kind of issues might appear.

**Comment by CooperCGN** [comment]
I am closing this, for some weird reason I had the homebridge instance running this plugin showing up as not responding. Removed it from my home and did a complete reinstall. It’s working now as expected.
