### ISSUE TITLE
Channel control like lightbulb

### ISSUE THREAD

**Issue by bx67212** [merdok/homebridge-webos-tv#323]
Hi,

Is possible to switch as volume control to light bulb to control channel?

**Comment by merdok** [comment]
Hi,
it would certainly be possible, but i am not sure if this is a good idea. 
You would only have a limit of 100 channels and besides that the on/off feature would be not used. I think that could just confuse people and i am not sure if it would be that intuitive. 
From another perspective it would certainly save some space since then it would not be necessary to create a new tile for each channel...

**Comment by bx67212** [comment]
@merdok yes it is only another prospective: before homebridge I use openhap and channel service is in lightbulb mode. It is usefully because its hard that people use more than 100 channel.
But it is also true that on/off feature would be not used.
If you can set a select mode for channel (for example lightbulb mode or button mode) and have both feature it is 🔥

**Comment by merdok** [comment]
Let me think about it. I mean adding that would not be an issue and of course it could be optional. I would just need to think for what useful thing I could use the on/off button of the lightbulb...

**Comment by bx67212** [comment]
I close because this is not an issue but only a suggest ;)

**Comment by NorthernMan54** [comment]
This has likely already been asked, but what about including channel as part of the input selector ?

This is from something I pulled together last year to control the RS-232 port on my LG TV.  I have since upgraded the TV to one that supports WebOS and doesn't have the RS-232 port anymore ;-(.  But the feature did have a good WAF score in my setup.

![image](https://user-images.githubusercontent.com/19808920/102397838-72548a80-3fac-11eb-9bbe-2ce51ae8eab4.png)

**Comment by merdok** [comment]
@NorthernMan54 Possible it would be, but i find it confusing to mix channels and inputs together. It does not really make sense then since Live TV is also an input. The spinner is meant to be for inputs...
