### ISSUE TITLE
Inputs limit reached!

### ISSUE THREAD

**Issue by kikher** [merdok/homebridge-webos-tv#330]
hello I have a LG 2020 TV with homekit integration and whenever I turn it on these yellow lines appear.
Can it be solved in any way?
Thank you very much for your great work.

<img width="841" alt="Captura de pantalla 2020-12-09 a las 13 47 40" src="https://user-images.githubusercontent.com/75734843/101631961-7c631000-3a25-11eb-921d-ffa8c818b82e.png">

**Comment by merdok** [comment]
Hello,

let me explain the issue. HomeKit has a limit of 100 services per accessory. Due to the fact how the plugin is build ( it allows a big amount of customization ) I have to reserve some services for the configuration. Basically every switch or input in the input spinner is a single service. Because of that I set a maximum limit of 45 for inputs which are fetched from the tv, this makes sure that the not all services are used up for inputs fetched from the tv, in that case you would not have any more switches available. 
You are getting this warning because you have more then 45 apps installed on your tv 😉 in most cases users do not have so many apps. You can ignore this warning or you could remove some unused apps from your tv in order to get rid of it. In the end the limit is there in order to make sure that everything is working and the warning is displayed so that you do not wonder why some inputs are missing.

**Comment by kikher** [comment]
Hi,
I get it, but the TV is new and I only have the basic apps, Disney +, HBO, Netflix and Amazon. I don't use anything else.

I have another LG TV from last year with the same apps and this does not happen.

Thanks for everything.

**Comment by merdok** [comment]
Well, the TV might have some hidden apps, this also includes system applications. You can enable the debug log to get more insight about what exactly is loading.

**Comment by kikher** [comment]
I got this in debug log

<img width="973" alt="Captura de pantalla 2020-12-09 a las 15 49 04" src="https://user-images.githubusercontent.com/75734843/101644978-221e7b00-3a36-11eb-9e0c-ba0b1d77994d.png">

**Comment by merdok** [comment]
You can now have a look at the cached inputs file which is located in the homebridge directory under .webosTv to check what inputs has been retrieved and cached or you could enable deepDebugLog to see exactly what inputs were fetched from the tv.

**Comment by kikher** [comment]
How can I do the deepDebugLog?  I have tried to fix it, I have deleted all the apps from the TV but the problem persists

**Comment by merdok** [comment]
Just check the README, there is an additional property in the config to enable that. What you can also try is to clear the webos tv inputs cache. It is located in the .homebridge/.webOsTv/ directory.
