### ISSUE TITLE
Sound adjustment with Home Theater 

### ISSUE THREAD

**Issue by tansuka** [merdok/homebridge-webos-tv#34]
Hello @merdok ,

As mentioned [here ](https://github.com/merdok/homebridge-webos3/issues/21#issuecomment-367281799), it's not possible to control volume if it's an external source connected through arc. It works flawlessly if sound is set to internal speaker but if I use my home theater, add on can't get and set the correct volume level. 

Thanks

**Comment by merdok** [comment]
I am not sure if it is possible to control the volume of external sources. I would need to check this out.

**Comment by quacktacular** [comment]
Just confirming this issue exists over ARC output. 

I noticed that the plugin is able to read the current volume. Its also able to mute / unmute.

```[2018-4-10 17:23:35] [TVbert] webOS - TV state: On
[2018-4-10 17:23:35] [TVbert] webOS - TV volume: 21
[2018-4-10 17:23:35] [TVbert] webOS - TV muted: No
[2018-4-10 17:23:35] [TVbert] webOS - TV state: On```

**Comment by quacktacular** [comment]
@merdok I noticed that volume up and down buttons in the LG app work as expcected. If this doesn’t work out would it be easy to add optional volume up and down switches? (Presumably using the API calls those button do)

**Comment by tansuka** [comment]
Hello @quacktacular and @merdok ,

Yes, Mute and unmute work flawlessly, I couldn't get TV Volume level (external source source level) during my tests. 
Since Volume up / down work, maybe we can still use brightness slider, iterate within a for loop and until volume is up to desired level send volume up command one by one. But it's crucial to have current volume level of the tv (external source) which I couldn't. 

Thanks

**Comment by merdok** [comment]
@quacktacular @tansuka 
Thanks for the info. So just to confirm, the issue is that you can't set or get the volume of external audio devices with the current volume switch, but the mute / unmute is working?

**Comment by quacktacular** [comment]
@merdok yes that is mostly correct.

In my case the plugin actually can read the volume, but just can't set it.

**Comment by merdok** [comment]
Ok. Unfortunately I don't have any external audio device to test it with, but i will see what i can do.

**Comment by quacktacular** [comment]
Sounds good. Let me know if I can anything to help. Happy to create a vm on my network for you to try if that would be helpful.

**Comment by merdok** [comment]
Should be possible with latest release, i have added volume up/down switches, could somebody please try it and let me know? Please note that i renamed the package to `homebridge-webos-tv`, so you need to install this new package and adjust your config.json

**Comment by quacktacular** [comment]
@merdok can confirm this is working! and much better than the hack I had written haha.

Can we also get a toggle to disable the lightbulb control?

**Comment by merdok** [comment]
@quacktacular Good to hear :) 

I thought of adding a toggle to switch between the lightbulb and those switches, but in the end i decided against it since this would just make the code more complicated, mostly because i would need to handle the mute switch differently. Also i would anyway had to add a 3rd switch for the mute button so why no to use the lightbulb. And finally with the lightbulb you know what the volume of your TV is, useful when you not at home and want to check the volume level.

**Comment by quacktacular** [comment]
@merdok I totally understand, but I've actually found the volume indicated on the light bulb isn't accurate. Worse when I try to control "all the lights" it always fails because of the volume bulb (which I can't turn off without disabling the new buttons as well).

 A boolean for the lightbulb would be enough, myself (and probably others) won't really mind the missing mute capability.

**Comment by merdok** [comment]
Will think about it. Thanks for the feedback!

**Comment by quacktacular** [comment]
Brilliant! Working great, thank you!
