### ISSUE TITLE
Mac as a TV

### ISSUE THREAD

**Issue by josephcomisi** [merdok/homebridge-webos-tv#341]
Hi there,

I was wondering if we could turn our Mac/PC as a HomeKit TV thanks to homebridge-webos-tv

Basically, interesting features to control would be:
- Volume Up/Down (Homebridge Pc Volume)
- Brightness Up/Down
- Sleep/Wake (Homebridge Standby Screen)
- Keyboard arrows (Up/Down/Left/Right)
- Ability to control these features via the HomeKit Remote
- Start apps (such as Apple TV +, Plex, Stremio)

The ultimate goal here would be to turn our Mac/PC into a TV/Media Player and control it via HomeKit

Any ideas, thoughts would be appreciated :)

PS: not the best place to put that, please let me know where we could discuss about that

**Comment by merdok** [comment]
Hi,

in theory that would be possible but you would need to also write an dedicated app for Mac/PC which then accepts the commands sent from HomeKit. I think this requires quite some work in order to get that working. Including that in this plugin is certainly not the right way to go, a new dedicated plugin for that scenario would need to be created.

**Comment by josephcomisi** [comment]
Ok, it answer my question then. I thought this plugin could do part of job, but got to start everything from scratch :) 

Thx vm merdok
