### ISSUE TITLE
Feature Request: Home Tile subtitle

### ISSUE THREAD

**Issue by dppeak** [merdok/homebridge-webos-tv#343]
Let me start off by saying Great Plugin.  Much better functionality then the native HomeKit support!

Not sure if this is possible, but it would be nice to have the subtitle on the Home App Tile for the TV to show the selected App/Input.  The default HomeKit tile for the TV (LG TV is new enough to have HomeKit support), show's the selected input as the subtitle.

For example, in the images below it would be nice to have it say Plex instead of "All On".

![IMG_5822B7602CC5-1](https://user-images.githubusercontent.com/868044/105608264-94d68200-5d68-11eb-84ff-fe2a5c112f4c.jpeg)
![IMG_EF1EED827EDE-1](https://user-images.githubusercontent.com/868044/105608265-956f1880-5d68-11eb-8f20-fc40bfa639cd.jpeg)

Thanks,
Dave

**Comment by merdok** [comment]
Thanks! This functionality is already there. What you are showing above is probably the TV accessory but this plugin per default creates a group. So in order to get the same effect you need to ungroup your TV accessories generated by this plugin and then you can put your TV accessory directly to your home screen with the subtitle. 
As far as i know i cannot change the groups subtitle....

**Comment by dppeak** [comment]
You're right.  Thanks!!
