### ISSUE TITLE
Add HomeKit Features

### ISSUE THREAD

**Issue by cartermw** [merdok/homebridge-webos-tv#347]
I’m currently using the plug-in LG webOS Tv
2.0.8 published 12/6/2020 

Shouldn’t I be able to add the play and pause tiles in my HomeKit like this picture? ![image](https://user-images.githubusercontent.com/65145948/108220239-259c4580-70fc-11eb-97ae-2fabf9bfffc3.jpeg)

**Comment by merdok** [comment]
Hi,

not sure if i understand you correctly, but you mean that the Play/Pause button is missing for you?
In that case, did you had a look at the https://github.com/merdok/homebridge-webos-tv#tv-configuration-fields section? 
In order to display the Play/Pause buttons you need to set the `mediaControl` property to `true`. This feature is disabled per default.

**Comment by cartermw** [comment]
Setting media control to true fixed it thank you￼.
