### ISSUE TITLE
Set eco/picture mode on LG C9

### ISSUE THREAD

**Issue by Luitwieler** [merdok/homebridge-webos-tv#356]
I checked out the code and saw an interesting class.
```
// not working, why?
  setSystemSettings() {
    this.lunaSend('luna://com.webos.service.settings/setSystemSettings', {
      category: "picture",
      dimension: {
        pictureMode: "eco"
      },
      settings: {
        brightness: 30
      }
    });
  } 
```
It is currently not implemented and I would really like to have it as a button in HomeKit. 

I am now using an insane button sequence to reach the same goal.

What kind of problems were you facing using this logic? It may give me some good direction to start debugging and develop a solution.

**Comment by KeyofBlueS** [comment]
https://github.com/merdok/homebridge-webos-tv/issues/322

**Comment by merdok** [comment]
Yeah, well as already mentioned before, LG has some internal services on their TVs which allow to actually do that. The issue is that those services are not published (or stripped down) on the public websocket API. 
So in short, there is no official public web api for that, and the code which you see is basically me experimenting and trying to find a workaround which i unfortunately did not find till today...

**Comment by TillmannD** [comment]
Do you get an error or whats the problem?

As in the webosose described, it should work: 
https://www.webosose.org/docs/reference/ls2-api/com-webos-service-settings/#setsystemsettings

**Comment by merdok** [comment]
@TillmannD this is a private api which is not accessible through the public webOS api.
Although i tried to do some tricks to call the private service it still does not work and i am not sure why.
