### ISSUE TITLE
Crashing HB service

### ISSUE THREAD

**Issue by ArtemKiyashko** [merdok/homebridge-webos-tv#381]
After a lot of experiments i realised this plugin crashing latest homebridge server just few second after launching. Disabling this plugin will stop infinite service restart and HB service working properly.

I also realised, that similar plugin (https://github.com/grzegorz914/homebridge-lgwebos-tv) running into same behaviour. So im not really sure where is the problem, maybe in some common dependency.

**Comment by infvmm** [comment]
Same issue here, with same problems on other lgwebos plugin. It happens in the moment of tv connecting. If you configure the plugin from scratch it works well until the moment you allow in the tv to connect to the tv, in that moment HB Service restart. 

This is the moment
[5/8/2021 14:02:00] [webostv] [Tele] Connected to TV
[5/8/2021 14:02:00] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGBUS
[5/8/2021 14:02:05] [HB Supervisor] Restarting Homebridge...

With debug mode i could get this also: 
[5/8/2021 14:05:41] [webostv] [Tele] Connected to TV
[5/8/2021 14:05:41] [webostv] [Tele] Requesting TV information
[5/8/2021 14:05:41] [webostv] [Tele] system service - getSystemInfo requested.
[5/8/2021 14:05:41] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGBUS
[5/8/2021 14:05:46] [HB Supervisor] Restarting Homebridge...

**Comment by merdok** [comment]
First of the other plugin is just a rip off of this plugin, so it will behave exactly the same as my plugin since he only copy/pasted it. 
Second i have the latest homebridge running and there are no crashes.
You said that the crash occurs straight after connecting, this might indicate that you simply do not have permissions to write to the file system. There are some configuration files which needs to be written to the file system, if you do not have the required permissions then such crash might occur. I would recommend to make sure that homebridge can write to the specified config directory and that should fix your issues.

**Comment by ArtemKiyashko** [comment]
Pls refer to issue with full story - https://github.com/grzegorz914/homebridge-lgwebos-tv/issues/102

I don’t care who is copy and who is paste :) I’m just trying to get it working

**Comment by infvmm** [comment]
@merdok thanks for your answer, but as we could realized the problem is the “arm_64=1” change on raspberry pi. I suppose you are not using raspberrypi as you are saying you have it running. If you could generate a version with more log I suppose @ArtemKiyashko and I could help you to solve it if you are interested on.

**Comment by merdok** [comment]
Again i do not care about the other plugin and i will not refer any stories from there since it has nothing to do with this here.

I am actually using the latest 64 bit Raspi OS on a raspberry pi. You can simple enable the "deepDebugLog" flag to generate a lot more output and paste it here.

**Comment by ArtemKiyashko** [comment]
okay, i enabled "deepBebugLog", tbh dont see any specific information in the output (maybe im looking in the wrong location?):
```
Starting to advertise 'My LG TV 3512' using bonjour-hap backend!
[05/08/2021, 20:09:05] My LG TV 3512 is running on port 44757.
[05/08/2021, 20:09:05] Please add [My LG TV 3512] manually in Home app. Setup Code: 775-27-736
Starting to advertise 'Homebridge 74A1' using bonjour-hap backend!
[05/08/2021, 20:09:05] Homebridge v1.3.4 (Homebridge) is running on port 51648.
[05/08/2021, 20:09:05] [webostv] [My LG TV] Connecting to TV
[05/08/2021, 20:09:05] [webostv] [My LG TV] Message from TV 

[05/08/2021, 20:09:05] [webostv] [My LG TV]  {
  type: 'utf8',
  utf8Data: '{"type":"registered","id":"a9ceb7920000","payload":{"client-key":"d11e9d5825b7df41257753f1d6cc6869"}}'
}
[05/08/2021, 20:09:05] [webostv] [My LG TV] Connected to TV
[05/08/2021, 20:09:05] [webostv] [My LG TV] Requesting TV information
[05/08/2021, 20:09:05] [webostv] [My LG TV] system service - getSystemInfo requested. 
[05/08/2021, 20:09:05] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGBUS
[05/08/2021, 20:09:10] [HB Supervisor] Restarting Homebridge...
[05/08/2021, 20:09:10] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[05/08/2021, 20:09:10] [HB Supervisor] Started Homebridge v1.3.4 with PID: 10085
Initializing HAP-NodeJS v0.9.4...
[05/08/2021, 20:09:11] Loaded config.json with 1 accessories and 7 platforms.
[05/08/2021, 20:09:11] Loaded 1 cached accessories from cachedAccessories.
```
Config:
```
{
            "devices": [
                {
                    "name": "My LG TV",
                    "ip": "192.168.1.56",
                    "mac": "60:AB:14:59:79:66",
                    "pollingInterval": 5,
                    "deepDebugLog": true,
                    "volumeLimit": 100,
                    "volumeControl": "both",
                    "channelControl": false,
                    "mediaControl": true
                }
            ],
            "platform": "webostv"
        }
```

Directory permissions also looks ok:
```
pi@homebridge:/var/lib/homebridge/.webosTv $ ls -la
total 20
drwxr-xr-x 2 homebridge homebridge 4096 Jun 18 00:03 .
drwxr-xr-x 8 homebridge homebridge 4096 Aug  5 20:03 ..
-rw-r--r-- 1 homebridge homebridge 1340 Jun 30 00:01 inputsAvailable_60AB14597966
-rw-r--r-- 1 homebridge homebridge 1661 Jun 18 00:03 inputsConfg_60AB14597966
-rw-r--r-- 1 homebridge homebridge   32 Aug  4 20:32 keyFile_192168156_60AB14597966
pi@homebridge:/var/lib/homebridge/.webosTv $ 
```

**Comment by merdok** [comment]
Your logs look pretty much normal which might indeed indicate that the error does not come from the plugin itself, also it seems that the config were also created successfully, which i guess confirms that the permissions are ok. 

So what i can tell for sure is that the error is not originating from my plugin, but from homebridge. Could you somehow check if you can provide some detailed crash log from homebridge to find out the cause why your homebridge is crashing?

**Comment by infvmm** [comment]
What i provided you is all the log i have, if i can share more info please let me know how....

**Comment by merdok** [comment]
I have just explained you above that i am using the 64 bit Raspi OS (this parameter needs to be enabled). If you are using 64 or 32 bit Raspberry pi os should have no effect on this plugin. I could eventually imagine that you are using an older version of nodejs which has limited 64 bit OS support, but this is just an assumption.

Till you do not provide a crash log then actually everything will just be an assumption. The log which you provided me above is from my plugin, for which we already determined that it is not the cause of the crash. The crash is originating from somewhere else (might be that it is from something else like a nodejs method), and in order to find out exactly from where you need to provide a correct crash log.

**Comment by ArtemKiyashko** [comment]
`64 bit Raspi OS (this parameter needs to be enabled) `
Maybe. But by default, in official Homebridge RPI 64bit Image it is disabled. That’s why we’re paying attention to this

**Comment by merdok** [comment]
Yes, and since I have it enabled and it works, and for you not, my suspicion could also be that some dependencies are not up to date on your side. I am pretty certain that for example nodejs needed to have an update to run on the arm64 bit version. It might be nodejs or something else, i cannot say for sure. Without a proper crash log this will just be speculation, so you would 
recommend  you to try to find out where the crash log from homebridge is stored. Since this is not a plugin crash you will not see any crash log in the console during startup.

**Comment by merdok** [comment]
@infvmm and @ArtemKiyashko i think i know now what your issue is.
Did you actually install the 64 Bit version of Raspberry Pi using the official image or did you just simply set the flag arm_64bit=1 in your boot.txt?
If you just set the flag and think that you are now running the 64 bit os then you are mistaken and that should be avoided!
Setting this flag is at this point not recommend since you are now mixing a 64 bit kernel with 32 bit software (homebridge) which causes your issues. Setting just the **arm_64bit=1** is not supported by homebridge.

**Comment by infvmm** [comment]
Hi @merdok i wrote you this as result of my uname -a: 
Linux **raspberrypi4** 5.10.52-v8+ #1440 SMP PREEMPT Tue Jul 27 09:56:40 BST 2021 **aarch64** GNU/Linux

I installed the official image, it would be good if you compare with yours as you are telling us you have the lastest version. At least we will know where the difference comes. @ArtemKiyashko If you execute uname -m you can see even as me the arch. 

On the other hand, we are not telling you is a problem of the plugin, but we enable the plugin HB fails or the plugin fails, not happen to me with the rest of pluggins i have had at least 8, 

You assumed this "for which we already determined that it is not the cause of the crash. The crash is originating from somewhere else", but we really don´t know, even without knowledge of your code. 

As you can realize is not very easy and fast for us debug this code, we are only asking you a test with this parameter. As you can see, we need this parameter (arm_64bit=1) even having an 64 arch. This is due to some kind of issue. 

You can read here https://www.raspberrypi.org/documentation/configuration/config-txt/boot.md it´s no necessary, but you can read: 
https://forum.libreelec.tv/thread/23667-le10-rpi4-4gb-oom-errors/?postID=155197#post155197
https://github.com/raspberrypi/linux/issues/3210

Reading this: https://github.com/homebridge/homebridge/issues/2783 what they are saying is config arm_64bit on a 32 bit linux, i think is not my case as you can see, i don´t know what more can i check

**Comment by ArtemKiyashko** [comment]
@infvmm 
```
pi@homebridge:/var/lib/homebridge/.webosTv $ uname -m 
aarch64
pi@homebridge:/var/lib/homebridge/.webosTv $ uname -a
Linux homebridge 5.10.52-v8+ #1440 SMP PREEMPT Tue Jul 27 09:56:40 BST 2021 aarch64 GNU/Linux
pi@homebridge:/var/lib/homebridge/.webosTv $ 
```

**Comment by infvmm** [comment]
@ArtemKiyashko  have you updated with a rpi-update and rpi-eeprom-update or have you installed from the lastest image?.

**Comment by merdok** [comment]
Yes, that confirms your issue, `aarch64 ` is not supported by homebridge at this point.
You can try to run your system with the arm_64bit=1 parameter but you will not get any support since this is simply not officially supported.
The issue which you are experiencing is not with a plugin but with homebridge itself simply not supporting that parameter. 

I have realized that i have this parameter disabled on my 64 bit installation that is why it is running for me.

**Comment by ArtemKiyashko** [comment]
@infvmm i`ve installed image appoximately 2-3 months ago, since that time i havent run rpi-update or eeprom update, just apt upgrade

**Comment by ArtemKiyashko** [comment]
Ok, as expected, nobody want to fix that =) If we will disable arm_64 - HB (probably) will work, but OOM Reaper gonna kill processes when it should not.

**Comment by merdok** [comment]
@ArtemKiyashko it was already announce by the homebridge team that it will be fixed as soon as the 64 bit os will be out of beta!

**Comment by ArtemKiyashko** [comment]
@infvmm that copy-pasted plugin after last update now working well
