### ISSUE TITLE
Power State Not updating in real time.. or even eventually

### ISSUE THREAD

**Issue by Claywd** [merdok/homebridge-webos-tv#412]
So when turning on the projector via ARC I'd like to get the status of the LG HU85LA WebOS 4.5 so I can trigger a shelf to slide out. When I click the power button everything shows up but otherwise it stays dark. 

Anyway to subscribe to power events from the device or at least poll for power states?

tia

**Comment by Claywd** [comment]
Looks like the code doesn't check for power state on init either. It would be a good/quick add.

**Comment by Claywd** [comment]
Thinking we should probably call the device for it's power state instead of checking if we are connected. Two very different functions. https://github.com/merdok/homebridge-webos-tv/blob/master/lib/LgTvController.js#L524-L529

Maybe call this instead of just checking if the device is connected. https://github.com/merdok/homebridge-webos-tv/blob/master/lib/LgTvController.js#L755-L757

**Comment by merdok** [comment]
Hi,

no, this not a good idea. Any requests to the tv(or projector) should be avoided during status updates since this might freeze the home ui.

Since the projector has webos4.5 the plugin should subscribe to power state updates, you say that does not happen? You could post a debug log so I can check if there is an error from the projector on why exactly that does not happen.

**Comment by Claywd** [comment]
my bad. I didn't see where we were subscribed to updates already.... https://github.com/merdok/homebridge-webos-tv/blob/master/lib/LgTvController.js#L285

after seeing that I started troubleshooting and there was a network issue. I set my router to give it a static ip but it apparently did not...  once I set it to the right IP in the device settings things started working a little better sort of... The delay between the power of the device and the plugin recognizing the state change is delayed...  

For reference I have it set to poll the device every 1s. 

I don't have a logfile for you though... even in debug mode there is no log fromt he plugin.. it either doesn't get an update from the projector or its not listening/polling anymore. If I attached the log file it would just be a bunch of other plugins updating verbosely.

Is there currently a flag to tell the code to post a log update on every poll for device state?

**Comment by Claywd** [comment]
Okay, I waited 5 minutes after turning on the projector with the remote, to try turning on in homekit and then I finally got some logs. When turning the device afterwards it worked immediately. So the issue seems to be when the device powers on there is a delay or no update by/at/in the plugin at all. 

[homebridge.log.txt](https://github.com/merdok/homebridge-webos-tv/files/7670859/homebridge.log.txt)

**Comment by merdok** [comment]
The log looks good and i do not see any issues there. The only obvious thing is that the plugin tries to subscribe to TV specific services which is unnecessary on the projector, but they still surprisingly are availabel on the projector and succeed.
Poll is only relevant for webOS 2.0 and lower devices where there is no power state service, and is only used in your case to check if the device went online. 
I think that the delay which you see when starting might be due to the projector starting up and it just takes some time till the device is available and can respond to requests.

**Comment by Claywd** [comment]
>I think that the delay which you see when starting might be due to the projector starting up and it just takes some time till the device is available and can respond to requests.

I thought the same thing at first but was able to confirm that this isn't the case. Subscription isn't working on startup of the device. I confirmed this by adding a homekit automation so that when my roku turns on  (keep in mind that my roku turns on the projector by HDMI ARC) homekit also tries to turn on the projector which is connected via this plugin. Since homekit lags by about 1-2s here is what happens. 

The roku turns on, the projector turns on (via Arc), which triggers my projector screen (by wireless dongle), roku status is updated in homekit, then the homekit automation fires which triggers the plugin to get the state of the projector, which finally triggers the second automation to slide the shelf out for the projector.  The projector responds to request.... otherwise the homekit automation wouldn't do anything... this plugin has to be told when to check for the projectors power on though. Its not working otherwise. I just made homekit tell it by using an automation and tieing it to the roku. 

But when I hook up my nintendo switch and turn on the projector, the shelf never slides out because the plugin has not been triggered in homekit to register that the projector is on. 

Definitely missing logic somewhere.

**Comment by merdok** [comment]
I unfortunately cannot test it myself since I do not have any webos projector, hence I can only guess and evaluate the information which you give me. From the log point of view everything looks fine and I do not see any obvious issues there which might cause the delay which you are speaking of, also the logic is certainly ok and working as it should(at least for TVs). 

Another guess could be the follow:
Whether the projector is on or off needs to be done by polling (pinging the ip of the projector), this is done per default in an 5 seconds interval, hence when you turn on the projector it might take up to 5 seconds (plus boot time of the projector to fire up all the services) till it actually shows online in HomeKit. This might cause the "delay" which you see and make your chain of triggers fail.
You have to keep it mind that it is not possible to connect to the projector instantly after it turns on since the whole os needs to start up which takes quite some time and I can imagine that the projector does not have as good hardware as the TVs. The powering on is triggered by a wake on lan packet which does not require the projector to be booted up, the wake on lan packet tells the projector to actually turn on.

You are also talking just about power on, that means after the device powers on and after some while you are able to control it from HomeKit without any issues I suppose? If that is the case, then my theory might be correct.

**Comment by Claywd** [comment]
>Whether the projector is on or off needs to be done by polling (pinging the ip of the projector), this is done per default in an 5 seconds interval, hence when you turn on the projector it might take up to 5 seconds (plus boot time of the projector to fire up all the services) till it actually shows online in HomeKit. This might cause the "delay" which you see and make your chain of triggers fail.

It worked once with a delay. All subsequent test have been no detection at all. The projector turns on and the plugin never recognizes it until I trigger it via homekit somehow. The log file up above was after I waited about 5 minutes to trigger it in homekit. 

>You have to keep it mind that it is not possible to connect to the projector instantly after it turns on

But it doesn't take 5 minutes for it to boot up, and the fact that the plugin never recognized when the device powered on indicates something is amiss. 

>You are also talking just about power on, that means after the device powers on and after some while you are able to control it from HomeKit without any issues I suppose? If that is the case, then my theory might be correct.

Power on is what I am most concerned about but no, none of the switches work after turning on the projector outside of homekit (via arc or remote) ... until I trigger the state change of the plugin manually by touching a button for plugin in homekit. I'll test for a delay with the other buttons and see if there is something I am missing. 

I should say that according to the logs, as soon as the projector turns on and my automation triggers the plugin to update I see plugin subscribe to events in the logs. It seems like the projector is immediately available after power on. I'll test some more and probably hack at the code a little in the evening this week.

**Comment by merdok** [comment]
If the plugin subscribes to the projectors events immediately after you power it on then the issue might lay somewhere else.

You could put some logs in various code places and see what the output is. I would recommend you to start in the index.js from line 1654 and see if everything is called there.
