### ISSUE TITLE
No power on after some time

### ISSUE THREAD

**Issue by Stetocasa** [merdok/homebridge-webos-tv#414]
Hi, the plug-in works very well, but if I not use the TV for some days, I cannot turn on the tv.
I'm obliged to turn on from my remote

**Comment by merdok** [comment]
Hi, i suppose this Is due to some power saving features of your tv or router. Make sure that you have all power saving features disabled. The TV needs to listen to network request all the time or it will not work. Some common tv settings which are required you can find on the bottom of the configuration section here https://github.com/merdok/homebridge-webos-tv#configuration

**Comment by Stetocasa** [comment]
> Hi, i suppose this Is due to some power saving features of your tv or router. Make sure that you have all power saving features disabled. The TV needs to listen to network request all the time or it will not work. Some common tv settings which are required you can find on the bottom of the configuration section here https://github.com/merdok/homebridge-webos-tv#configuration

This happen also wit LG app, not just plug-in issue

**Comment by merdok** [comment]
Then this just confirms that the issue is either a configuration issue with your TV or network. Like i already said you need to disable all power saving features on your tv and network and recheck the configuration.
