### ISSUE TITLE
Has 'channelButtons' been removed from the UI

### ISSUE THREAD

**Issue by mm98** [merdok/homebridge-webos-tv#448]
Hi!,

First of all. Thanks for this awesome plugin!

I've noticed that it isn't a possibility anymore, to have `channelButtons` in HomeKit (after the lastes release). No option is availavle in the Homebridge UI. Previously, channels from 1-9 was automaticly added under the TV icon. Is this intentional or am I doing something wrong?

_TV: LG OLED C1 (latest webos)_

**Comment by merdok** [comment]
Hi, not quite sure what you mean, but the section is still available in homebridge ui and you can add/remove channel buttons there.

**Comment by mm98** [comment]
TLD; I changed my channels trough the UI (which requires more props per channel). Which means i got it working. 

If you look at the [Configuration](https://github.com/merdok/homebridge-webos-tv#configuration) section in the `README.md`. The JSON node `channelButtons` is shown with the following JSON example. 

```json
"channelButtons": [ 
   3,
   5,
   7
]
```

This was also how my `channelButtons` (json) was defined. But, this is not the format the UI uses anymore - so these values are not visible/rendered in the UI under `Channel buttons` (blank empty).

**Comment by merdok** [comment]
There are a couple of ways to set the channelButtons. The easiest way is to specific just the channel number and that's all, there is also a more complex way where you can fine tune some parameters. The complex way is used in the ui, and when you use the simple way in the json it will not be recognized on the ui. This behavior is like that since a couple of years now so it is nothing new actually.
