### ISSUE TITLE
Change name of TV Screen

### ISSUE THREAD

**Issue by L041S** [merdok/homebridge-webos-tv#487]
Hello,
By default the name of the TV screen button in Apple Home is "Screen". I renamed it but each time homebridge is restarted, it goes back to the original "Screen" name. Is it possible to have an option to change it to something else by adding a "name:" setting in the json like for appbuttons ?

**Comment by merdok** [comment]
There are some issues with names since iOS16, it was possible to rename it before but initially all the names were the same. Now i did a workaround to fix the names but that causes the issue that when you rename a switch and restart homebridge it will revert back... I will try to have a look and come up with something.

**Comment by L041S** [comment]
Hello, I saw that the issue was marked as completed but even after the latest update 2.4.2 it keeps losing the name after reboot.
Is there something to do in config file ?

**Comment by merdok** [comment]
Hi, the behavior did not change in the latest update, i do not consider it a bug but a necessary workaround currently. To remove the workaround i would need to do some bigger code changes... I keep it in my mind but not sure when i will have the time to tackle that.
