### ISSUE TITLE
Picture Mode Status Not Updating When Changed Manually

### ISSUE THREAD

**Issue by iSteve-O** [merdok/homebridge-webos-tv#510]
I love the new status-aware picture mode buttons, but I’ve noticed that if I change the picture mode manually with the tv remote the status doesn’t update in the home app. Also, if I turn on a currently unavailable picture mode I would expect it to turn off and the active status to turn on but this doesn’t happen either. 

A small part of the problem may be related to polling, but it would not explain all of it. In my experience with my plugin I found behavior like this related to caching of the status response. My issue in my plugin was that if I turned a switch off in the home app, but based on the response that switch was supposed to be on, it wouldn’t come back on in the home app because the server response was unchanged. If the plugin caches the status response when polling, and the status changes in the home app but the server response hasn’t actually changed, the home app will not update status properly. I was at first using ‘longpoll’ in my plugin and when I switched to just ‘poll’ this behavior was corrected because poll gets a fresh response every time but longpoll only gets a fresh response only if the response has actually changed. I’m not sure if this is applicable, or even similar but I thought it couldn’t hurt to mention.

**Comment by merdok** [comment]
Unfortunately the tv does not notify about picture mode changes, also it does not report which picture mode is currently set. In the recent update there was PR from someone who recommended to cache the last selected picture mode and show that on the picture mode button (mark the selected one). I mean that now works correctly but only if you use the homekit buttons to control that.
So due to that, there is really nothing that i can do about it... The only solution would be to find a way to get the current active picture mode from the tv, but as far as my research and api reverse engineering go, there is no way to do it...

**Comment by iSteve-O** [comment]
That makes total sense. I really appreciate your explanation & totally understand. Thanks for all your hard work on it!
