### ISSUE TITLE
How to tune digital channels?

### ISSUE THREAD

**Issue by bwalls** [merdok/homebridge-webos-tv#94]
How do I specify digital channels in the channel list?

For instance, we have channel 48-1, 48-2, 48-3, and 48-4 over the air. 

I first tried 48.1, 48.2, 48.3, and 48.4 in the list. This would seem to work, in that the TV would how being of 48-1, 48-2, but wasn't actually on the channel. It was close enough that going up or down would get there.

using 48-1 or 48\-1 in the list doesn't work. I'm assuming only integers are allowed in the list?

using 48 gets me to 48-1, and I can channel up to the others. But wondering if I'm just missing a convention on how to designate digital channels.

**Comment by merdok** [comment]
Basically you are right, a channel can be only an integer. I am not sure if you can navigate to a channel with such a channel number. 
Since i never saw such channel numbers before this confuses me. How do you even navigate to channel 48-3 with the remote??
What you could do is start homebridge in debug mode and try to switch channels with the remote, after that paste the log here so i can see what are channel numbers reported by the TV.

**Comment by bwalls** [comment]
I actually figured it out. A channel does __not__ have to be an integer. It can be a string. Here is my current setting:
```
		"channelButtons": ["15-1", "19-1", "19-2", "19-3", "25-1", "25-2", "25-3", "25-4", "25-5", "31-1", "31-2", "31-3", "48-1", "48-2", "48-3", "48-4", "54-1", "54-2", "54-3", "54-4", 141, 146, 362],
```
On the Magic Remote, the "-List" button is actually either "-" or "List", depending on context. So when you are typing in a number, you can enter "1"-"9"-"-"-"2" to get to 19-2 on the remote.

This was all new to me!

I recommend putting a couple of strings in the example text in the readme.

**Comment by merdok** [comment]
Good that it works! Thanks for letting me know!
